name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Quando houver push na branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Ambiente de execução (Ubuntu)

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2  # Faz o checkout do repositório

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Instala o Node.js
        with:
          node-version: '22.14.0'  # Define a versão do Node.js que seu projeto usa

      - name: Install dependencies
        run: npm install  # Instala as dependências

      - name: Build the project
        run: npm run build  # Gera a pasta 'build/'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Ação que envia para o GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Token de autenticação
          publish_dir: ./build  # Diretório a ser enviado para o GitHub Pages
